resources:
  - name: nix-build-task-git
    type: git
    source:
      uri: https://github.com/risicle/nix-build-task.git
      branch: master
  - name: nix-build-task-pipeline-git
    type: git
    source:
      uri: https://github.com/risicle/nix-build-task.git
      branch: master
      paths:
        - ci/

jobs:
  - name: update-pipeline
    serial: true
    plan:
    - get: nix-build-task-pipeline-git
      trigger: true
    - set_pipeline: nix-build-task-build
      file: ci/build.yml

  - name:
    serial: true
    plan:
      - get: nix-build-task-git
        trigger: true
      - task: build
        image_resource:
          type: registry-image
          source:
            repository: risicle/nix-build-task
        inputs:
          - name: nix-build-task-git
        outputs:
          - name: output
        params:
          NIXFILE: nix-build-task-git/
          ATTR: imageConcourse
        run:
          path: /bin/build
