on:
  push:
    branches: [ master ]

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: tag-and-attempt-push
      run: |
        PUSH_OUT=$(mktemp)
        git tag "v$(cat ./VERSION)"
        git push origin "v$(cat ./VERSION)" 2>&1 | tee "$PUSH_OUT" || grep -Fi 'already exists' "$PUSH_OUT"
